instagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from post.views import home_view

urlpatterns = [
    url(r'^$',home_view, name='post_list'),
    url(r'^aadmin/', admin.site.urls),
    url(r'^post/', include(('post.urls', 'post'), namespace='post')),
    url(r'^member/', include(('member.urls', 'member'), namespace='member')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

member/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

from . import views

from .api import UserViewSet

app_name = 'member'

router = routers.DefaultRouter()
router.register('members', UserViewSet)

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^api/doc$', get_swagger_view(title='Rest API Document')),
    url(r'^api/v1/', include((router.urls, 'member'), namespace='api')),
]

post/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

from . import views

from .api import PostViewSet

app_name = 'post'

router = routers.DefaultRouter()
router.register('post', PostViewSet)

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^product/$', views.productView, name='product'),
    url(r'^export/$', views.export_csv, name='export_csv') ,
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^add/', views.post_add, name='post_add'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^api/doc$', get_swagger_view(title='Rest API Document')),
    url(r'^api/v1/', include((router.urls, 'post'), namespace='api')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Instagram</title>
</head>
<body>
<nav class="top-nav navbar navbar-static-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'post:post_list' %}" class="navbar-brand">Instagram</a>
        </div>
        <div class="collapse navbar-collapse">
            <form action="" class="navbar-form navbar-left search-hashtag-form" role="search">
                <div class="form-group">
                    <input type="text" class="form-control search-hashtag-input" placeholder="해시태그 검색...">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-nav-scroll">
                {% if user.is_authenticated %}
                    <li><a href="">Likes</a></li>
                    <li><a href="">Profile</a></li>
                    <li><a href="{% url 'member:logout' %}">Logout</a></li>
                        <div class="navbar-header navbar-form navbar-right navbar-btn">
                             <a class="add-post" href="{% url 'post:post_add' %}"><button type="button" class="btn btn-info ">Add Post</button></a>
                        </div>

{#                    <div class="header">#}
{#                    </div>#}
                {% else %}
                    <li><a href="{% url 'member:login' %}">Login</a></li>
                    <li><a href="{% url 'member:signup' %}">Signup</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
{#<ul class="nav navbar-nav navbar-right">#}
{#	{% if user.is_authenticated %}#}
{#	<li><a href="">Likes</a></li>#}
{#	<li><a href="">Profile</a></li>#}
{#	<li><a href="{% url 'member:logout' %}">Logout</a></li>#}
{#	{% else %}#}
{#	<li><a href="{% url 'member:login' %}">Login</a></li>#}
{#	<li><a href="">Signup</a></li>#}
{#	{% endif %}#}
{#</ul>#}
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert-message alert
					{% if message.tags == 'info' %}
						alert-info
					{% elif message.tags == 'success' %}
						alert-success
					{% elif message.tags == 'warning' %}
						alert-warning
					{% elif message.tags == 'error' %}
						alert-danger
					{% endif %}
					">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <h1>{% block title %}{% endblock %}</h1>

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/base_home.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
    <title>Home</title>
</head>
<body>
<div class="header">
</div>{% if user.is_authenticated %}

    <h1>Kante's Blog</h1>
    <div class="recent">Recent Posts</div>
    <div class="container">
    <ul class="list">
    {% for post in posts %}
        <li>
            <div class="title"><a href="/post/{{ post.pk }}">{{ post.title }}</a></div>
        </li>
    {% endfor %}
{% else %}
    <li><button type="button" class="btn btn-default btn-lg"><a href="{% url 'member:login' %}">Login</a></button></li>
{% endif %}

</ul>
</div>
</body>
</html>