instagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from post.views import home_view

urlpatterns = [
    url(r'^$',home_view, name='post_list'),
    url(r'^aadmin/', admin.site.urls),
    url(r'^post/', include(('post.urls', 'post'), namespace='post')),
    url(r'^member/', include(('member.urls', 'member'), namespace='member')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

post/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

from . import views

from .api import PostViewSet

app_name = 'post'

router = routers.DefaultRouter()
router.register('post', PostViewSet)

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^product/$', views.productView, name='product'),
    url(r'^export/$', views.export_csv, name='export_csv') ,
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^add/', views.post_add, name='post_add'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^api/doc$', get_swagger_view(title='Rest API Document')),
    url(r'^api/v1/', include((router.urls, 'post'), namespace='api')),
]

post/models.py
from django.conf import settings
from django.db import models
from datetime import datetime
from django.db import models
from django_pandas.managers import DataFrameManager
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    photo = models.ImageField(upload_to='post',default = "SOME STRING")
    title = models.CharField(max_length=100, blank=True)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Post (PK: {self.pk}, Author: {self.author.username})'

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    class Meta:
        ordering = ['-pk']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    content = models.TextField()

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'


class Product(models.Model):
    product_name = models.TextField()
    objects = models.Manager()
    pdobjects = DataFrameManager()  # Pandas-Enabled Manager

post/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'photo',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'content',
                    'placeholder': '댓글 달기...',
                }
            )
        }

    def clean_content(self):
        data = self.cleaned_data['content']
        errors = []
        if data == '':
            errors.append(forms.ValidationError('댓글 내용을 입력해주세요'))
        elif len(data) > 50:
            errors.append(forms.ValidationError('댓글 내용은 50자 이하로 입력해주세요'))
        if errors:
            raise forms.ValidationError(errors)
        return data

post/views.py
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CommentForm
from .models import Post
from django.contrib import messages
from .forms import PostForm
from django.contrib.auth.decorators import login_required
import pandas as pd
import io
from .revisit_from_created_at_users import make_dataframe
from django.contrib.auth import get_user_model
import csv
from django.contrib.auth.models import User


def home_view(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'base_home.html', context)



def post_list(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)

# def comment_create(request, post_pk):
#     # 요청 메서드가 POST방식 일 때만 처리
#     if request.method == 'POST':
#         # Post인스턴스를 가져오거나 404 Response를 돌려줌
#         post = get_object_or_404(Post, pk=post_pk)
#         # request.POST에서 'content'키의 값을 가져옴
#         comment_form = CommentForm(request.POST)
#         # 올바른 데이터가 Form인스턴스에 바인딩 되어있는지 유효성 검사
#         if comment_form.is_valid():
#             # 유효성 검사에 통과하면 Comment객체 생성 및 DB저장
#             Comment.objects.create(
#                 post=post,
#                 # 작성자는 현재 요청의 사용자로 지정
#                 author=request.user,
#                 content=comment_form.cleaned_data['content']
#             )
#         # 정상적으로 Comment가 생성된 후
#         # 'post'네임스페이스를 가진 url의 'post_list'이름에 해당하는 뷰로 이동
#         return redirect('post:post_list')


@login_required
def comment_create(request, post_pk):
    # GET파라미터로 전달된 작업 완료 후 이동할 URL값
    next_path = request.GET.get('post/post_detail.html')

    # 요청 메서드가 POST방식 일 때만 처리
    if request.method == 'POST':
        # Post인스턴스를 가져오거나 404 Response를 돌려줌
        post = get_object_or_404(Post, pk=post_pk)
        # request.POST데이터를 이용한 Bounded Form생성
        comment_form = CommentForm(request.POST)
        # 올바른 데이터가 Form인스턴스에 바인딩 되어있는지 유효성 검사
        if comment_form.is_valid():
            # 유효성 검사에 통과하면 ModelForm의 save()호출로 인스턴스 생성
            # DB에 저장하지 않고 인스턴스만 생성하기 위해 commit=False옵션 지정
            comment = comment_form.save(commit=False)
            # CommentForm에 지정되지 않았으나 필수요소인 author와 post속성을 지정
            comment.post = post
            comment.author = request.user
            # DB에 저장
            comment.save()

            # 성공 메시지를 다음 request의 결과로 전달하도록 지정
            messages.success(request, '댓글이 등록되었습니다')
        else:
            # 유효성 검사에 실패한 경우
            # 에러 목록을 순회하며 에러메시지를 작성, messages의 error레벨로 추가
            error_msg = '댓글 등록에 실패했습니다\n{}'.format(
                '\n'.join(
                    [f'- {error}'
                     for key, value in comment_form.errors.items()
                     for error in value]))
            messages.error(request, error_msg)

        # next parameter에 값이 담겨 온 경우, 해당 경로로 이동
        if next_path:
            return redirect(next_path)
        # next parameter가 빈 경우 post_list뷰로 이동
        return redirect('post:post_list')


# @login_required
# def post_create(request):
#     if request.method == 'POST':
#         # PostForm은 파일을 처리하므로 request.FILES도 함께 바인딩
#         post_form = PostForm(request.POST, request.FILES)
#         if post_form.is_valid():
#             User = get_user_model()
#             print(User.objects.first)
#             print("@@@@@@@@@@@1")
#             author = User.objects.get(username='kante')
#             title = request.POST.get('title','TLSLDA')
#             print("@@@@@@@@@@@1")
#             content = request.POST ['content']
#             print("@@@@@@@@@@@2")
#             # author = User.objects.get(username=request.user)
#             # author필드를 채우기 위해 인스턴스만 생성
#             post = Post.objects.create(
#                 # Post 객체의 author 필드에 'author' 변수 할당
#                 author=author,
#                 title=title,
#                 content=content,
#             )
#             print(post.title)
#             print("@@@@@@@@@@@3")
#             # author필드를 채운 후 DB에 저장
#             post.save()
#             print("@@@@@@@@@@@3")
#
#             # 성공 알림을 messages에 추가 후 post_list뷰로 이동
#             messages.success(request, '사진이 등록되었습니다')
#             return redirect('post:post_list')
#     else:
#         post_form = PostForm()
#
#     context = {
#         'post_form': post_form,
#     }
#     return render(request, 'post/post_create.html', context)


def productView(request):
    df = make_dataframe()
    # df = pd.DataFrame([1000, 2000, 3000, 4000], index=["i1", "i2", "i3", "i4"])
    # df.to_html
    # qs = Product.pdobjects.all()  # Use the Pandas Manager
    # df = qs.to_dataframe()
    template = 'post/product.html'
    # Format the column headers for the Bootstrap table, they're just a list of field names,
    # duplicated and turned into dicts like this: {'field': 'foo', 'title: 'foo'}
    # columns = [{'field': f, 'title': f} for f in df]
    # Write the DataFrame to JSON (as easy as can be)
    # json = df.to_json(orient='records')  # output just the records (no fieldnames) as a collection of tuples
    # Proceed to create your context object containing the columns and the data
    # context = {
    #          'data': json,
    #          'columns': columns
    #         }
    # And render it!
    return render(request, template, {'context' : df.to_html })


def export_csv(request, df_input):
    sio = io.StringIO
    df = df_input
    PandasWriter = pd.ExcelWriter(sio, engine = 'xlswriter')
    df.to_excel(PandasWriter, sheet_name='pdf')
    PandasWriter.save()

    sio.seek(0)
    workbook = sio.getvalue()

    response = StreamingHttpResponse(workbook, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=%s' % 'output.csv'
    return response


# @login_required
# def post_add(request):
#     print("@@@@@@@@@   start    @@@@@@@@@@@@@@@@")
#     if request.method == 'POST':
#         print("@@@@@@@@@   0    @@@@@@@@@@@@@@@@")
#         post_form = PostForm(request.FILES)
#         print("@@@@@@@@@   1    @@@@@@@@@@@@@@@@")
#         # if post_form.is_valid():
#         print("@@@@@@@@@   2    @@@@@@@@@@@@@@@@")
#         User = get_user_model()
#         print("@@@@@@@@@   3    @@@@@@@@@@@@@@@@")
#         author = User.objects.get(username='kante')
#         print("@@@@@@@@@   4   @@@@@@@@@@@@@@@@")
#         title = request.POST['title']
#         print("@@@@@@@@@   5    @@@@@@@@@@@@@@@@")
#         content = request.POST['content']
#         print("@@@@@@@@@   6    @@@@@@@@@@@@@@@@")
#         context = {
#             'author' : author,
#             'title' : title,
#             'post_form': post_form,
#             'content' : content,
#         }
#         post = Post.objects.create(
#             photo = context['post_form'],
#             author = context['author'],
#             title = context['title'],
#             content = context['content'],
#         )
#
#         print("@@@@@@@@@   8    @@@@@@@@@@@@@@@@")
#         post.save()
#         messages.success(request, '사진이 등록되었습니다')
#         return render(request, 'post/post_add.html', context)
#     elif request.method == 'GET':
#         return render(request, 'post/post_add.html')

@login_required
def post_add(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

            User = get_user_model()
            print(request.user.password)
            post = form.save(commit=False)
            post.title = request.POST['title']
            post.content = request.POST['content']
            post.author = User.objects.get(username = request.user.username)
            post.save()
            messages.success(request, '새 글이 등록되었습니다.')
            return redirect('post:post_list')

    else:
        form = PostForm()
    return render(request, 'post/post_add.html', {
        'form': form,
    })

@login_required
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.FILES)
        if post_form.is_valid():
            User = get_user_model()
            user_id = int(request.POST['id'])
            user = User.objects.get(id=user_id)
            print(user)
            author = User.objects.get(username='kante')
            title = request.POST['title']
            print(title.name)
            content = request.POST['content']
            post = Post.objects.create(
                author=author,
                title=title,
                content=content,
            )
            print(post.title)


            messages.success(request, '사진이 등록되었습니다')
            context = {
                'post_form': post_form,
            }
            post.save()
            return render(request, 'post/post_create.html', context)
    else:
        post_form = PostForm()

    context = {
        'post_form': post_form,
    }
    return render(request, 'post/post_create.html', context)


def post_delete(request, pk):
    if request.method == 'POST':
        print(pk)
        post = Post.objects.get(pk=pk)
        post.delete()
        return render(request, 'post/post_delete.html')

    elif request.method == 'GET':
        return HttpResponse('잘못된 접근 입니다.')

templates/post/post_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="form-container account-form-container">
        <form class="form account-form" action="" method="post" enctype="multipart/form-data">
            {#<form action="" method="post">#}

            <h2 class="post-add">새 글 작성</h2>

            <div class="form-group">
                <label for="input-title">제목: </label>
                <input name="title" id="input-title" type="text" class="form-control" placeholder="글 제목">
            </div>
            <div class="form-group">
                <label for="input-content">내용: </label>
                <textarea name="content" id="input-content" class="form-control" rows="5" placeholder="글 내용"></textarea>
            </div>

            {#        <button type="submit" class="btn btn-primary btn-lg">글 등록</button>#}
            <div class="preview">
                <div class="upload">
                    <span class="preview-bg"></span>
                    <p class="preview-title">포스트 이미지 추가</p>
{#                    {% if post %}#}
{#                        <p><img id="blah" src="{{ post.photo_url|default_if_none:'#'}}" style="width: 300px; height: 300px; object-fit: cover" ></p>#}
{#                    {% else %}#}
{#                        <p><img id="blah" src="" style="width: 300px; height: 300px; object-fit: cover" ></p>#}
{#                    {% endif %}#}
                </div>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            {#    <input class="submit_btn" type="submit" value="저장">#}

            {% include 'include/form.html' with form=post_form submit_title='글 등록' enctype='file' %}
            {#  </form>#}
            {#</div>#}
            {#	{% include 'include/form.html' with form=post_form submit_title='글 등록' enctype='file' %}#}

        </form>
    </div>
{#    <script type="text/javascript">#}
{#        function upload_img(input) {#}
{#            if (input.files && input.files[0]) {#}
{#                var reader = new FileReader();#}
{#                reader.onload = function (e) {#}
{#                    $('#img_id').attr('src', e.target.result);#}
{#                }#}
{#                reader.readAsDataURL(input.files[0]);#}
{#            }#}
{#            $(".preview-bg").remove();#}
{#            $(".preview-title").remove();#}
{#        }#}
{#        $("#id_photo").change(function(){#}
{#            upload_img(this);#}
{#        });#}
{#        $(document).on('click', '.upload', function(){#}
{#            $("#id_photo").click();#}
{#        });#}
{#        $('#id_photo').attr("required", true);#}
{#    </script>#}
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $("#img_id").on('change', function(){
                readURL(this);
            });
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                    $('#blah').attr('src', e.target.result);
                }

              reader.readAsDataURL(input.files[0]);
            }
        }


    </script>

{% endblock %}

templates/post/post_create.html
{% extends 'base.html' %}

{% block title %}Post create{% endblock %}
{% block content %}
     {% csrf_token %}

<div class="post-create">
        <div class="form-group">
                    <label for="input-title">제목: </label>
                    <input name="title" id="input-title" type="text" class="form-control" placeholder="글 제목">
                </div>
        <div class="form-group">
            <label for="input-content">내용: </label>
            <textarea name="content" id="input-content" class="form-control" rows="5" placeholder="글 내용"></textarea>
        </div>

	{% include 'include/form.html' with form=post_form submit_title='등록' enctype='file' %}
</div>

{% endblock %}

templates/post/post_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>글이 삭제되었습니다.</h1>
    <a href="/">
        <button type="button" class="btn btn-primary to-main">To Main</button>
    </a>
</div>
{% endblock %}

templates/post/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div id="post-{{ post.pk }}">
        {% include 'include/post.html' with post_type='list' %}
        <p class="text-right"><span class="glyphicon glyphicon-star" aria-hidden="true"></span><em>{{ post.created_at }}</em></p>
    </div>
    <a href="/">
        <button type="button" class="btn btn-primary to-main">To Main</button>
    </a>
    <form action="{% url 'post:post_delete' pk=post.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Post</button>
    </form>
    </div>

{% endblock %}

{##}
{#{% load static %}#}
{#<!doctype html>#}
{#<html lang="ko">#}
{#<head>#}
{#	<meta charset="UTF-8">#}
{#	<meta name="viewport"#}
{#	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
{#	<meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
{#	<link rel="stylesheet" href="{% static 'css/style.css' %}">#}
{#	<title>Instagram</title>#}
{#</head>#}
{#<body>#}
{#	<div class="container">#}
{#		{% if messages %}#}
{#			{% for message in messages %}#}
{#				<div class="alert-message alert#}
{#					{% if message.tags == 'success' %}#}
{#						alert-success#}
{#					{% elif message.tags == 'error' %}#}
{#						alert-danger#}
{#					{% endif %}#}
{#					">{{ message }}</div>#}
{#			{% endfor %}#}
{#		{% endif %}#}
{##}
{#		<div class="panel panel-default post-item">#}
{#			<img src="{{ post.photo.url }}" alt="" class="post-image">#}
{#			<div class="panel-body">#}
{#				{% if post.comments.exists %}#}
{#				<ul class="comment-list">#}
{#					{% for comment in post.comments.all %}#}
{#					<li class="comment">#}
{#						<span class="comment-author">{{ comment.author }}</span>#}
{#						<span class="comment-content">{{ comment.content }}</span>#}
{#					</li>#}
{#					{% endfor %}#}
{#				</ul>#}
{#				<hr>#}
{#				{% endif %}#}
{#				<form action="{% url 'post:comment_create' post_pk=post.pk %}" method="POST" class="comment-form">#}
{#					{% csrf_token %}#}
{#					{{ comment_form.content }}#}
{#				</form>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#</body>#}
{#</html>#}

templates/post/post_list.html
{% extends 'base.html' %}

{% block title %}Post List{% endblock %}
{% block content %}
<div class="row">
	{% for post in posts %}
		<div id="post-{{ post.pk }}">
			{% include 'include/post.html' with post_type='list' %}
		</div>
	{% endfor %}
</div>
{% endblock %}
{##}
{#{% load static %}#}
{#<!doctype html>#}
{#<html lang="ko">#}
{#<head>#}
{#	<meta charset="UTF-8">#}
{#	<meta name="viewport"#}
{#	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
{#	<meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
{#	<link rel="stylesheet" href="{% static 'css/style.css' %}">#}
{#	<title>Instagram</title>#}
{#</head>#}
{#<body>#}
{#	<div class="container">#}
{#		<h1>Post List</h1>#}
{##}
{##}
{#		{% for post in posts %}#}
{#			<div class="panel panel-default post-item">#}
{#            <a href="{% url 'post:post_detail' post_pk=post.pk %}"><img src="{{ post.photo.url }}" alt="" class="post-image">#}
{#</a>#}
{#				<img src="{{ post.photo.url }}" alt="" class="post-image">#}
{#				<div class="panel-body">#}
{#                    <form action="{% url 'post:comment_create' post_pk=post.pk %}" method="POST" class="comment-form">#}
{#                        {% for comment in post.comments.all %}#}
{#                            <div class="comment">#}
{#                                <div class="date">{{ comment.created_date }}</div>#}
{#                                <strong>{{ comment.author }}</strong>#}
{#                                <p>{{ comment.content}}</p>#}
{#                                </div>#}
{#                        {% empty %}#}
{#                            <p>No comments here yet :(</p>#}
{#                        {% endfor %}#}
{#				{% csrf_token %}#}
{#				<input type="text" name="content" placeholder="댓글 달기...">#}
{#			</form>#}
{#				</div>#}
{#			</div>#}
{#		{% endfor %}#}
{#	</div>#}
{##}
{#</body>#}
{#</html>#}

templates/post/product.html
<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>#}
{#<script src='/static/js/jquery.js'>#}
{#<script src='/static/js/bootstrap-table.js'>#}
{#<script src='/static/js/pandas_bootstrap_table.js'>#}
{#<table id='datatable'>{% include 'include/pd_html.html' with class='table-hover'%}</table>#}
{#<table id='datatable'>{{ context }}</table>#}
{#<div id="i_result">document.getElementById("i_result").innerHTML={{ context }};</div>#}
{% autoescape off %}{{ context }}{% endautoescape %}
{#<a href="{% url 'post:' %}">Export all users</a>#}
<!-- Yep, all you need is a properly identified
     but otherwise empty, table tag! -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>